name: keklist
description: Like TODO-List but keklist

publish_to: "none"

version: 4.5.0+116

environment:
  sdk: ">=3.10.0"

dependencies:
  adaptive_dialog: ^2.0.0
  bloc: ^9.0.0
  blur: ^4.0.0
  calendar_date_picker2: ^2.0.1
  cross_file: ^0.3.3+4
  csv: ^6.0.0
  cupertino_icons: ^1.0.5
  emojis: ^0.9.9
  encrypt: ^5.0.3
  equatable: ^2.0.5
  fast_immutable_collections: ^11.0.3
  fl_chart: ^1.0.0
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_animate: ^4.1.1+1
  flutter_bloc: ^9.0.0
  flutter_easyloading: ^3.0.5
  flutter_emoji: ^2.4.0
  flutter_simple_dependency_injection: ^2.0.0
  flutter_svg: ^2.0.5
  form_field_validator: ^1.1.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  intl: ^0.20.2
  file_picker: ^8.0.5
  modal_bottom_sheet: ^3.0.0-pre
  package_info_plus: ^9.0.0
  path_provider: ^2.0.12
  photo_manager: ^3.8.3
  photo_manager_image_provider: ^2.2.0
  photo_view: ^0.15.0
  pointycastle: ^3.9.1
  just_audio: ^0.9.40
  rxdart: ^0.28.0
  scrollable_positioned_list: ^0.3.5
  settings_ui: ^2.0.2
  share_plus: ^12.0.0
  syncfusion_flutter_charts: ^31.1.22
  url_launcher: ^6.1.9
  uuid: ^4.2.1
  video_player: ^2.10.1
  webview_flutter: ^4.1.0
  wechat_assets_picker: ^10.1.0
  gap: ^3.0.1
  #home_widget: ^0.6.0
  #workmanager: ^0.5.2
  flutter_dotenv: ^6.0.0
  flutter_staggered_grid_view: ^0.7.0
  bottom_sheet: ^4.0.0
  action_sheet: ^1.0.4
  archive: ^4.0.7
  haptic_feedback: ^0.5.1+1
  provider: ^6.1.2
  collection: ^1.18.0
  local_auth: ^2.2.0
  translator: ^1.0.0
  telegram_web_app: ^0.3.3
  auto_size_text: ^3.0.0
  scrollview_observer: ^1.26.0
  streaming_shared_preferences: ^2.0.0
  json_serializable: ^6.8.0
  json_annotation: ^4.9.0
  swipeable_page_route: ^0.4.8
  image_picker: ^1.2.0
  logarte: ^1.4.0
  purchases_flutter: ^9.8.0
  purchases_ui_flutter: ^9.8.0
  record: ^6.1.2
  just_waveform: ^0.0.7
  flutter_gen: ^5.9.0

dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.0
  hive_generator: ^2.0.0
  build_runner: ^2.3.3 #dart run build_runner build --delete-conflicting-outputs
  intl_utils: ^2.8.2

flutter:
  generate: true
  uses-material-design: true
  assets:
    - dotenv
    # - assets/auth_icons/
    # - assets/steganograph_image/
